name: Deploy Development API

on:
  push:
    branches:
      - develop
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g serverless
      - run: yarn --production
      # - run: cd src/utils/airdrop && yarn && cd ../../../
      - run: serverless deploy -s ${GITHUB_REF#refs/heads/}
        env:
          NODE_ENV: develop
          BRANCH: ${GITHUB_REF#refs/heads/}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD_DEVELOP }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME_DEVELOP }}
          JWT_NAMESPACE: ${{ secrets.JWT_NAMESPACE_DEVELOP }}
          JWT_SECRET: ${{ secrets.JWT_SECRET_DEVELOP }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY_DEVELOP }}
          SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL_DEVELOP }}
          SENDGRID_VERIFICATION_TEMPLATE: ${{ secrets.SENDGRID_VERIFICATION_TEMPLATE_DEVELOP }}
          SENDGRID_RESET_PASSWORD_TEMPLATE: ${{ secrets.SENDGRID_RESET_PASSWORD_TEMPLATE_DEVELOP }}
          WEB_APP_URL: ${{ secrets.WEB_APP_URL_DEVELOP }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS_DEVELOP }}
          WALLET_PUBLIC_KEY: ${{ secrets.WALLET_PUBLIC_KEY_DEVELOP }}
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY_DEVELOP }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY_DEVELOP }}
          MARKETPLACE_ADDRESS: ${{ secrets.MARKETPLACE_ADDRESS_DEVELOP }}
          NFT_ADDRESS: ${{ secrets.NFT_ADDRESS_DEVELOP }}
          AUCTION_ADDRESS: ${{ secrets.AUCTION_ADDRESS_DEVELOP }}
          AUCTION_V2_ADDRESS: ${{ secrets.AUCTION_V2_ADDRESS_DEVELOP }}
          NFT_MULTIPLE_EDITION_ADDRESS: ${{ secrets.NFT_MULTIPLE_EDITION_ADDRESS_DEVELOP }}
          MARKETPLACE_MULTIPLE_EDITION_ADDRESS: ${{ secrets.MARKETPLACE_MULTIPLE_EDITION_ADDRESS_DEVELOP }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY_DEVELOP }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET_DEVELOP }}
          MUX_TOKEN_ID: ${{ secrets.MUX_TOKEN_ID_DEVELOP }}
          MUX_TOKEN_SECRET: ${{ secrets.MUX_TOKEN_SECRET_DEVELOP }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          MAGIC_PRIVATE_KEY: ${{ secrets.MAGIC_PRIVATE_KEY_DEVELOP }}
          MUX_DATA_ID: ${{ secrets.MUX_DATA_ID_DEVELOP }}
          MUX_DATA_SECRET: ${{ secrets.MUX_DATA_SECRET_DEVELOP }}
          POLYGON_SCAN_API_KEY: ${{ secrets.POLYGON_SCAN_API_KEY_DEVELOP }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY_DEVELOP }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Trigger migrate lambda function
        run: |
          aws lambda invoke --function-name soundchain-api-develop-migrate response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
