name: Deploy Production API

on:
  push:
    branches:
      - production
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g serverless
      - run: yarn
      # - run: cd src/utils/airdrop && yarn && cd ../../../
      - run: serverless deploy -s ${GITHUB_REF#refs/heads/}
        env:
          NODE_ENV: production
          BRANCH: ${GITHUB_REF#refs/heads/}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD_PRODUCTION }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME_PRODUCTION }}
          JWT_NAMESPACE: ${{ secrets.JWT_NAMESPACE_PRODUCTION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET_PRODUCTION }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY_PRODUCTION }}
          SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL_PRODUCTION }}
          SENDGRID_VERIFICATION_TEMPLATE: ${{ secrets.SENDGRID_VERIFICATION_TEMPLATE_PRODUCTION }}
          SENDGRID_RESET_PASSWORD_TEMPLATE: ${{ secrets.SENDGRID_RESET_PASSWORD_TEMPLATE_PRODUCTION }}
          WEB_APP_URL: ${{ secrets.WEB_APP_URL_PRODUCTION }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS_PRODUCTION }}
          WALLET_PUBLIC_KEY: ${{ secrets.WALLET_PUBLIC_KEY_PRODUCTION }}
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY_PRODUCTION }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY_PRODUCTION }}
          MARKETPLACE_ADDRESS: ${{ secrets.MARKETPLACE_ADDRESS_PRODUCTION }}
          NFT_ADDRESS: ${{ secrets.NFT_ADDRESS_PRODUCTION }}
          AUCTION_ADDRESS: ${{ secrets.AUCTION_ADDRESS_PRODUCTION }}
          AUCTION_V2_ADDRESS: ${{ secrets.AUCTION_V2_ADDRESS_PRODUCTION }}
          NFT_MULTIPLE_EDITION_ADDRESS: ${{ secrets.NFT_MULTIPLE_EDITION_ADDRESS_PRODUCTION }}
          MARKETPLACE_MULTIPLE_EDITION_ADDRESS: ${{ secrets.MARKETPLACE_MULTIPLE_EDITION_ADDRESS_PRODUCTION }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY_PRODUCTION }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET_PRODUCTION }}
          MUX_TOKEN_ID: ${{ secrets.MUX_TOKEN_ID_PRODUCTION }}
          MUX_TOKEN_SECRET: ${{ secrets.MUX_TOKEN_SECRET_PRODUCTION }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          MAGIC_PRIVATE_KEY: ${{ secrets.MAGIC_PRIVATE_KEY_PRODUCTION }}
          MUX_DATA_ID: ${{ secrets.MUX_TOKEN_ID_PRODUCTION }}
          MUX_DATA_SECRET: ${{ secrets.MUX_TOKEN_SECRET_PRODUCTION }}
          POLYGON_SCAN_API_KEY: ${{ secrets.POLYGON_SCAN_API_KEY_PRODUCTION }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY_PRODUCTION }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Trigger migrate lambda function
        run: |
          aws lambda invoke --function-name soundchain-api-production-migrate response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_REGION: us-east-1
